// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mocks/mock_audit.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	audit "github.com/prbllm/go-metrics/internal/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsObserver is a mock of MetricsObserver interface.
type MockMetricsObserver struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsObserverMockRecorder
	isgomock struct{}
}

// MockMetricsObserverMockRecorder is the mock recorder for MockMetricsObserver.
type MockMetricsObserverMockRecorder struct {
	mock *MockMetricsObserver
}

// NewMockMetricsObserver creates a new mock instance.
func NewMockMetricsObserver(ctrl *gomock.Controller) *MockMetricsObserver {
	mock := &MockMetricsObserver{ctrl: ctrl}
	mock.recorder = &MockMetricsObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsObserver) EXPECT() *MockMetricsObserverMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMetricsObserver) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockMetricsObserverMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMetricsObserver)(nil).Close))
}

// Process mocks base method.
func (m *MockMetricsObserver) Process(ctx context.Context, event audit.AuditEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Process", ctx, event)
}

// Process indicates an expected call of Process.
func (mr *MockMetricsObserverMockRecorder) Process(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockMetricsObserver)(nil).Process), ctx, event)
}
