// Code generated by github.com/prbllm/go-metrics/cmd/reset; DO NOT EDIT.

package testdata

func (rs *ResetableStruct) Reset() {
	if rs == nil {
		return
	}
	rs.i = 0
	rs.str = ""
	if rs.strP != nil {
		*rs.strP = ""
	}
	rs.s = rs.s[:0]
	clear(rs.m)
	if rs.child != nil {
		rs.child.Reset()
	}
}